service: todo-api

runtime: nodejs
env: flex

runtime_config:
  operating_system: ubuntu22

basic_scaling:
  max_instances: 1
  idle_timeout: 10m

resources:
  cpu: 1
  memory_gb: 0.8
  disk_size_gb: 10