steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "--build-arg", "JWT_SECRET=$$JWT_SECRET",
      "--build-arg", "JWT_EXPIRES=$$JWT_EXPIRES",
      "--build-arg", "SALT_ROUNDS=$$SALT_ROUNDS",
      "--build-arg", "API_PORT=$$API_PORT",
      "--build-arg", "DB_HOST=$$DB_HOST",
      "--build-arg", "DB_USERNAME=$$DB_USERNAME",
      "--build-arg", "DB_PASSWORD=$$DB_PASSWORD",
      "--build-arg", "DB_NAME=$$DB_NAME",
      "--build-arg", "CORS_ORIGINS=$$CORS_ORIGINS",
      "--build-arg", "BASE_PATH=$$BASE_PATH",
      "--build-arg", "BUCKET_NAME=$$BUCKET_NAME",
      "-t", "${_IMAGE_NAME}", "."
    ]
    secretEnv: [
      "JWT_SECRET",
      "JWT_EXPIRES",
      "SALT_ROUNDS",
      "API_PORT",
      "DB_HOST",
      "DB_USERNAME",
      "DB_PASSWORD",
      "DB_NAME",
      "CORS_ORIGINS",
      "BASE_PATH",
      "BUCKET_NAME"
    ]

  - name: "gcr.io/cloud-builders/docker"
    args: [ "push",  "${_IMAGE_NAME}" ]

  - name: "gcr.io/cloud-builders/gcloud"
    args: [ "app", "deploy", "--image-url=${_IMAGE_NAME}" ]

timeout: "2400s"

options:
  automapSubstitutions: true
  dynamicSubstitutions: true

availableSecrets:
  secretManager:
    - versionName: "projects/${PROJECT_NUMBER}/secrets/JWT_SECRET/versions/2"
      env: "JWT_SECRET"
    - versionName: "projects/${PROJECT_NUMBER}/secrets/JWT_EXPIRES/versions/1"
      env: "JWT_EXPIRES"
    - versionName: "projects/${PROJECT_NUMBER}/secrets/SALT_ROUNDS/versions/1"
      env: "SALT_ROUNDS"
    - versionName: "projects/${PROJECT_NUMBER}/secrets/API_PORT/versions/1"
      env: "API_PORT"
    - versionName: "projects/${PROJECT_NUMBER}/secrets/DB_HOST/versions/1"
      env: "DB_HOST"
    - versionName: "projects/${PROJECT_NUMBER}/secrets/DB_USERNAME/versions/1"
      env: "DB_USERNAME"
    - versionName: "projects/${PROJECT_NUMBER}/secrets/DB_PASSWORD/versions/1"
      env: "DB_PASSWORD"
    - versionName: "projects/${PROJECT_NUMBER}/secrets/DB_NAME/versions/1"
      env: "DB_NAME"
    - versionName: "projects/${PROJECT_NUMBER}/secrets/CORS_ORIGINS/versions/1"
      env: "CORS_ORIGINS"
    - versionName: "projects/${PROJECT_NUMBER}/secrets/BASE_PATH/versions/1"
      env: "BASE_PATH"
    - versionName: "projects/${PROJECT_NUMBER}/secrets/BUCKET_NAME/versions/1"
      env: "BUCKET_NAME"