name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

      - name: "Get app version"
        id: "info"
        uses: "jaywcjlove/github-action-package@main"

      - name: "Set IMAGE_NAME environment variable"
        run: |-
          echo "IMAGE_NAME=${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ steps.info.outputs.version }}" >> $GITHUB_ENV

      - name: "Build image"
        run: "docker build . --file ./Dockerfile --tag ${{ env.IMAGE_NAME }}"

      - name: "Push image"
        run: "docker push ${{ env.IMAGE_NAME }}"

      - name: "Deploy in App Engine"
        run: |-
          gcloud app deploy --image-url=${{ env.IMAGE_NAME }}